sudo: required

env:
  - COMPOSE_VERSION: 1.8.0

before_script:
  - make init-test

script:
  - make phpunit
  
after_success:
  - docker-compose run -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -e TRAVIS="$TRAVIS" gbtest vendor/bin/php-coveralls -v
