version: '3'
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_USER: "guestbook"
      MYSQL_PASSWORD: "guestbook"
      MYSQL_ROOT_PASSWORD: "gbroot"
    volumes:
      - ./environment/mysql:/var/lib/mysql
      - ./environment/init_sql:/docker-entrypoint-initdb.d
    networks:
      ugyved-central-backend:
        aliases:
          - gb-net

  gbweb:
    build:
      context: ./environment/web
    links:
      - mysql
    environment:
      APPLICATION_ENV: "dev"
    ports:
      - '8080:80'
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/html
      - ${VHOSTS_DIR-./environment/web/vhosts}:/etc/apache2/sites-enabled
  gbtest:
    image: "zerosuxx/php-dev:7.2.9-cli"
    links:
      - mysql
    environment:
      APPLICATION_ENV: "test"
    volumes:
      - .:/opt/project
networks:
  gb-net:
    external: true

